version: "3"
services: 
  app:
    container_name: app
    build:
      context: ./
      dockerfile: app/Dockerfile
    tty: true
    volumes:
      - .:/portfolio
    ports:
      - "8080:8080"  
    # depends_on: 
    #   - db
  
  # db:
  #   container_name: db
  #   build: ./docker/db
  #   environment: 
  #     - MYSQL_ROOT_PASSWORD=password
  #   ports:   
  #     - "3306:3306"
  #   # volumes:
  #   #   - ./db/data:/var/lib/mysql

  # web:
  #   container_name: web
  #   build: ./docker/web
  #   ports:   
  #     - "80:80"
      