version: "3"
services: 
  app:
    container_name: app
    build:
      context: ./
      dockerfile: app/Dockerfile
    tty: true
    volumes:
      - .:/portfolio
    ports:
      - "8080:8080"  
    depends_on: 
      - db
  
  db:
    container_name: db
    build:
      context: ./
      dockerfile: db/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: go_database
      MYSQL_USER: go_test
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    volumes:
      - ./db/db-data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:   
      - "3306:3306"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  front:
    container_name: front
    build:
      context: ./
      dockerfile: front/Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./front:/front:cached
      - ./front/node_modules:/front/node_modules
    tty: true
    stdin_open: true
    command: yarn dev
      