version: "3"
services: 
  go:
    container_name: go
    build:
      context: ./
      dockerfile: go/Dockerfile
    tty: true
    ports:
      - "8080:8080"  
    depends_on: 
      - db
  
  db:
    container_name: db
    image: mysql:8.0
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: portfolio_user
      MYSQL_PASSWORD: portfolio_password
      TZ: 'Asia/Tokyo'
    volumes:
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf  
    ports:   
      - "3306:3306"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  front:
    container_name: front
    build:
      context: ./
      dockerfile: front/Dockerfile
    tty: true
    ports:
      - 3000:3000
    stdin_open: true
    command: npm run dev